//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_Laptops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Orderid { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<double> OrderBill { get; set; }
        public Nullable<double> OrderUnitPrice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
